### ISSUE TITLE
Invalid query string

### ISSUE THREAD

**Issue by wayt** [RafaelKeramidas/SAMPApp#1]
As describe on this page, http://wiki.sa-mp.com/wiki/Query_Mechanism, each query should contains the server IP and port.

But, since you use a String to build the pktdata, some signed hexadecimal value can not be set, so they are replaced by '?' character.

Here is a tcpdump trace:

```
80.12.55.53.60514 > 178.32.243.120.7777: UDP, length 15
0x0000:  4500 002b 0000 4000 3411 19e8 500c 3735  E..+..@.4...P.75
0x0010:  b220 f378 ec62 1e61 0017 7174 5341 4d50  ...x.b.a..qtSAMP
0x0020:  3f20 3f78 611e 7031 3233 34              ?.?xa.p1234
```

We've got 3f20 3f78 instead of b220 f378 for the IP.

This can also happen with the port value.

**Comment by RafaelKeramidas** [comment]
Hello,

Thanks for pointing that out, I will fix it for the next release.

Cheers,
Rafael.
